matrix:
  include:
    - language: java
      dist: trusty
      sudo: false
      before_script:
        - cd product-store
      script:
        - mvn clean verify

    - language: node_js
      dist: trusty
      node_js:
        - '5.6'
      sudo: required
      before_install:
        - npm install -g npm@5.6.0
        - npm install -g angular-cli
      before_script:
        - cd product-store-web
      script:
        - npm install
        - ng build