matrix:
  include:
    - language: java
      dist: trusty
      jdk:
        - openjdk8
      sudo: false
      before_script:
        - cd product-store
      script:
        - mvn clean verify

    - language: node_js
      dist: trusty
      node_js:
        - '5.6'
      sudo: required
      before_script:
        - cd product-store-web
      script:
        - npm install
        - ng build