version: '2'

services:
  store:
    image: productstore
    restart: always
    container_name: product-store
    environment:
      - VIRTUAL_HOST=local.product-store.com
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
    networks:
      store-network:
        ipv4_address: 172.10.0.6
#    network_mode: "bridge"
  nginx-proxy:
    image: nginx-proxy
    restart: always
    container_name: nginx-server
    ports:
      - "80:80"
    networks:
      store-network:
        ipv4_address: 172.10.0.5


networks:
  store-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.0.1