version: '2'

services:
  store:
    image: productstore
    restart: always
    container_name: product-store
    environment:
      - VIRTUAL_HOST=local.product-store.com
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
    networks:
      store-network:
        ipv4_address: 172.11.0.3

networks:
  store-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.11.0.0/16
         gateway: 172.11.0.1