version: '2'

services:
  nginx:
    image: nginxstore
    restart: always
    container_name: nginx-store
    networks:
      store-network:
        ipv4_address: 172.11.0.3

  store:
    image: productstore
    restart: always
    container_name: product-store
    networks:
      store-network:
        ipv4_address: 172.11.0.4
    volumes_from:
    - store-db

  store-db:
    image: productstore-db
    restart: always
    container_name: product-store-db
    networks:
      store-network:
        ipv4_address: 172.11.0.6
    volumes:
    - /var/lib/postgresql/data

  store-web:
    image: productstore-web
    restart: always
    container_name: product-store-web
    networks:
      store-network:
        ipv4_address: 172.11.0.2

  usermngmt:
    image: usermngmt
    container_name: usermngmt
    restart: always
    networks:
      store-network:
        ipv4_address: 172.11.0.5


  store-web:
    image: productstore-web
    restart: always
    container_name: productstore-web
    networks:
      store-network:
        ipv4_address: 172.11.0.2

  usermngmt:
    image: usermngmt
    container_name: usermngmt
    networks:
      store-network:
        ipv4_address: 172.11.0.5


networks:
  store-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.11.0.0/16
         gateway: 172.11.0.1